SSP: "SSP2"

emissions:
  carbonbudget: False
  baseline carbon intensity: False

economics:
  PRTP: 0.015 # 0.01
  elasmu: 1.001
  disutility_dmg_factor: 1.00001
  damages:
    scale factor: 2 #1
    ignore damages: False
    quantile: 0.5 # Only used for COACCH
    coacch_slr_withadapt: True # Only used for COACCH
